### ISSUE TITLE
List-item oplossing voor juiste formaat afbeelding 

### ISSUE THREAD

**Issue by Stefan-Espant** [Naddybs/the-startup-responsive-interactieve-website#10]
Hierbij stuur ik je de css oplossing voor jouw list-item

```css
.card {
    position: relative;
    overflow: hidden;
    border-radius: 10em 10em 10px 10px ;
    border-style: solid;
    border-color: rgba(33, 40, 41, 0.319);
    border-width: 1em;
    height: 30rem;
}

.card img {
    width: 20em;
    height: 20rem;
    aspect-ratio: 1/1;
    display: block;
    object-fit: cover;
 }
 ```
